### ISSUE TITLE
🛑 Game Server - karp.pokemon3d.net is down

### ISSUE THREAD

**Issue by dsbilling** [P3D-Legacy/status.pokemon3d.net#5]
In [`65a34c8`](https://github.com/P3D-Legacy/status.pokemon3d.net/commit/65a34c81595ab2aabd4f760b21dc186a83814ab1
), Game Server - karp.pokemon3d.net (karp.pokemon3d.net) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by Aragas** [comment]
Was me, server is restarted
